---
- name: Configure application server baseline
  hosts: tier_application
  become: true
  gather_facts: true
  serial: 1
  max_fail_percentage: 0

  roles:
    - role: common
      tags:
        - common
        - baseline

    - role: application
      tags:
        - application
        - deployment
