---
- name: Configure enterprise application instances
  hosts: tier_application
  become: true
  gather_facts: true

  roles:
    - role: common
      tags:
        - common

    - role: database_client
      tags:
        - database

    - role: application
      tags:
        - application
